2024-07-30T13:10:29.997627+00:00 app[web.1]: apps.populate(settings.INSTALLED_APPS)
2024-07-30T13:10:29.997627+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/django/apps/registry.py", line 91, in populate
2024-07-30T13:10:29.997627+00:00 app[web.1]: app_config = AppConfig.create(entry)
2024-07-30T13:10:29.997627+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^
2024-07-30T13:10:29.997627+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/django/apps/config.py", line 193, in create
2024-07-30T13:10:29.997627+00:00 app[web.1]: import_module(entry)
2024-07-30T13:10:29.997627+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/importlib/__init__.py", line 90, in import_module
2024-07-30T13:10:29.997628+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2024-07-30T13:10:29.997628+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-30T13:10:29.997628+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2024-07-30T13:10:29.997628+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2024-07-30T13:10:29.997628+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
2024-07-30T13:10:29.997628+00:00 app[web.1]: ModuleNotFoundError: No module named 'debug_toolbar'
2024-07-30T13:10:29.997713+00:00 app[web.1]: [2024-07-30 13:10:29 +0000] [9] [INFO] Worker exiting (pid: 9)
2024-07-30T13:10:29.998144+00:00 app[web.1]: [2024-07-30 13:10:29 +0000] [10] [ERROR] Exception in worker process
2024-07-30T13:10:29.998145+00:00 app[web.1]: Traceback (most recent call last):
2024-07-30T13:10:29.998145+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
2024-07-30T13:10:29.998145+00:00 app[web.1]: worker.init_process()
2024-07-30T13:10:29.998146+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/workers/base.py", line 134, in init_process
2024-07-30T13:10:29.998146+00:00 app[web.1]: self.load_wsgi()
2024-07-30T13:10:29.998146+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
2024-07-30T13:10:29.998146+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2024-07-30T13:10:29.998146+00:00 app[web.1]: ^^^^^^^^^^^^^^^
2024-07-30T13:10:29.998156+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/base.py", line 67, in wsgi
2024-07-30T13:10:29.998156+00:00 app[web.1]: self.callable = self.load()
2024-07-30T13:10:29.998156+00:00 app[web.1]: ^^^^^^^^^^^
2024-07-30T13:10:29.998157+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2024-07-30T13:10:29.998157+00:00 app[web.1]: return self.load_wsgiapp()
2024-07-30T13:10:29.998157+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^
2024-07-30T13:10:29.998157+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2024-07-30T13:10:29.998157+00:00 app[web.1]: return util.import_app(self.app_uri)
2024-07-30T13:10:29.998157+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-30T13:10:29.998158+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/util.py", line 359, in import_app
2024-07-30T13:10:29.998158+00:00 app[web.1]: mod = importlib.import_module(module)
2024-07-30T13:10:29.998158+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-30T13:10:29.998158+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/importlib/__init__.py", line 90, in import_module
2024-07-30T13:10:29.998158+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2024-07-30T13:10:29.998158+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-30T13:10:29.998159+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2024-07-30T13:10:29.998159+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2024-07-30T13:10:29.998159+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
2024-07-30T13:10:29.998159+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
2024-07-30T13:10:29.998159+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 995, in exec_module
2024-07-30T13:10:29.998159+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2024-07-30T13:10:29.998160+00:00 app[web.1]: File "/app/artful/wsgi.py", line 16, in <module>
2024-07-30T13:10:29.998160+00:00 app[web.1]: application = get_wsgi_application()
2024-07-30T13:10:29.998160+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^
2024-07-30T13:10:29.998161+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2024-07-30T13:10:29.998161+00:00 app[web.1]: django.setup(set_prefix=False)
2024-07-30T13:10:29.998161+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/django/__init__.py", line 24, in setup
2024-07-30T13:10:29.998161+00:00 app[web.1]: apps.populate(settings.INSTALLED_APPS)
2024-07-30T13:10:29.998161+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/django/apps/registry.py", line 91, in populate
2024-07-30T13:10:29.998161+00:00 app[web.1]: app_config = AppConfig.create(entry)
2024-07-30T13:10:29.998162+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^
2024-07-30T13:10:29.998162+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/django/apps/config.py", line 193, in create
2024-07-30T13:10:29.998162+00:00 app[web.1]: import_module(entry)
2024-07-30T13:10:29.998162+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/importlib/__init__.py", line 90, in import_module
2024-07-30T13:10:29.998162+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2024-07-30T13:10:29.998163+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-30T13:10:29.998163+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2024-07-30T13:10:29.998163+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2024-07-30T13:10:29.998163+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
2024-07-30T13:10:29.998163+00:00 app[web.1]: ModuleNotFoundError: No module named 'debug_toolbar'
2024-07-30T13:10:29.998279+00:00 app[web.1]: [2024-07-30 13:10:29 +0000] [10] [INFO] Worker exiting (pid: 10)
2024-07-30T13:10:30.079258+00:00 app[web.1]: Traceback (most recent call last):
2024-07-30T13:10:30.079260+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 209, in run
2024-07-30T13:10:30.079392+00:00 app[web.1]: self.sleep()
2024-07-30T13:10:30.079415+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 357, in sleep
2024-07-30T13:10:30.079493+00:00 app[web.1]: ready = select.select([self.PIPE[0]], [], [], 1.0)
2024-07-30T13:10:30.079560+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-30T13:10:30.079564+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2024-07-30T13:10:30.079621+00:00 app[web.1]: self.reap_workers()
2024-07-30T13:10:30.079634+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2024-07-30T13:10:30.079717+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2024-07-30T13:10:30.079742+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2024-07-30T13:10:30.079743+00:00 app[web.1]: 
2024-07-30T13:10:30.079744+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2024-07-30T13:10:30.079745+00:00 app[web.1]: 
2024-07-30T13:10:30.079754+00:00 app[web.1]: Traceback (most recent call last):
2024-07-30T13:10:30.079754+00:00 app[web.1]: File "/app/.heroku/python/bin/gunicorn", line 8, in <module>
2024-07-30T13:10:30.079785+00:00 app[web.1]: sys.exit(run())
2024-07-30T13:10:30.079804+00:00 app[web.1]: ^^^^^
2024-07-30T13:10:30.079814+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
2024-07-30T13:10:30.079847+00:00 app[web.1]: WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2024-07-30T13:10:30.079866+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/base.py", line 231, in run
2024-07-30T13:10:30.079920+00:00 app[web.1]: super().run()
2024-07-30T13:10:30.079934+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/app/base.py", line 72, in run
2024-07-30T13:10:30.079966+00:00 app[web.1]: Arbiter(self).run()
2024-07-30T13:10:30.079981+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 229, in run
2024-07-30T13:10:30.080028+00:00 app[web.1]: self.halt(reason=inst.reason, exit_status=inst.exit_status)
2024-07-30T13:10:30.080049+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 340, in halt
2024-07-30T13:10:30.080111+00:00 app[web.1]: def halt(self, reason=None, exit_status=0):
2024-07-30T13:10:30.080111+00:00 app[web.1]: 
2024-07-30T13:10:30.080112+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
2024-07-30T13:10:30.080164+00:00 app[web.1]: self.reap_workers()
2024-07-30T13:10:30.080176+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
2024-07-30T13:10:30.080258+00:00 app[web.1]: raise HaltServer(reason, self.WORKER_BOOT_ERROR)
2024-07-30T13:10:30.080272+00:00 app[web.1]: gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
2024-07-30T13:10:30.147740+00:00 heroku[web.1]: Process exited with status 1
2024-07-30T13:10:30.168624+00:00 heroku[web.1]: State changed from up to crashed
